<section class="intro">
    <p>Hello !</p>
    <p>moi c'est Anne-Laure</p>
    <img src="public/img/woman_laptop_2.jpg">
</section>
<section class="catch_text">
    <pre><</pre>
    <article>
    <p><span class="let">let</span> Développeuse, Intégratrice Web;</p> 
    <p><span>await</span> contrat d'apprentissage <span>||</span> contrat de professionnalisation;</p>
    <p><span>for</span> 3 semaines en entreprise pour 1 semaine de cours</p>
    </article>
    <pre>/></pre>
</section>